In [2]:
# import libraries

import numpy as np
import math
import sklearn as sk
import pandas as pd
from scipy import stats
import researchpy as rp
import seaborn as sn

In [3]:
lex = pd.read_excel('lex_assess_test.xlsx')

In [4]:
lex = lex[(lex.participant != 'P32')]

In [5]:
lex

   participant dyslexic  reading_score  pseudo_score  pseudo_rate
0          P01       no            4.7           NaN          NaN
1          P04       no            4.4           NaN          NaN
2          P07       no            5.1           NaN          NaN
3          P08       no            5.5           NaN          NaN
4          P11       no            7.0           NaN          NaN
5          P14       no            4.9           NaN          NaN
6          P15       no            7.1           NaN          NaN
7          P20       no            7.1           NaN          NaN
8          P21       no            6.1           NaN          NaN
9          P22       no            4.7           NaN          NaN
10         P23      yes            5.2          17.0     0.447368
11         P24      yes            3.5          10.0     0.263158
12         P25      yes            4.9          20.0     0.526316
13         P26      yes            3.0          14.0     0.368421
14         P27      yes            3.3          12.0     0.315789
15         P28      yes            4.6          13.0     0.342105
16         P29      yes            3.9          11.0     0.289474
17         P30      yes            3.5           7.0     0.184211
18         P31      yes            2.3          10.0     0.263158
20         P33      yes            2.1           8.0     0.210526
21         P34      yes            3.2          19.0     0.500000
22         P35      yes            4.3          16.0     0.421053
23         P36      yes            0.7           4.0     0.105263
24         P37      yes            4.8          13.0     0.342105
25         P38      yes            3.8          20.0     0.526316
26         P39      yes            3.2          14.0     0.368421
27         P40      yes            3.1           6.0     0.157895
28         P41      yes            4.0          10.0     0.263158

In [6]:
# store groups individually
non_dys = lex.iloc[:10]
dys = lex.iloc[10:]

In [7]:
dys.describe()

       reading_score  pseudo_score  pseudo_rate
count      18.000000     18.000000    18.000000
mean        3.522222     12.444444     0.327485
std         1.104832      4.718203     0.124163
min         0.700000      4.000000     0.105263
25%         3.125000     10.000000     0.263158
50%         3.500000     12.500000     0.328947
75%         4.225000     15.500000     0.407895
max         5.200000     20.000000     0.526316

In [8]:
dys.pseudo_score.quantile(0.1)

6.7

In [9]:
non_dys.describe()

       reading_score  pseudo_score  pseudo_rate
count        10.0000           0.0          0.0
mean          5.6600           NaN          NaN
std           1.0793           NaN          NaN
min           4.4000           NaN          NaN
25%           4.7500           NaN          NaN
50%           5.3000           NaN          NaN
75%           6.7750           NaN          NaN
max           7.1000           NaN          NaN

In [10]:
def ttest_score(feature):
    dys_data = dys[feature]
    nondys_data = non_dys[feature]

    score = rp.ttest(dys_data, nondys_data, equal_variances=True)
    t = score[1]['results'][2] 
    p = score[1]['results'][3]
    
    print(score)
    
    print("\nsignifinance testing of feature:", feature)
    print("t-test score:", t)
    print("p-value:", "{0:.15f}".format(p))

    if p < 0.05:
        print("difference between dyslexic and nondyslexic: significant")
    else:
        print("difference between dyslexic and nondyslexic: insignificant")

In [11]:
ttest_score('reading_score')

(        Variable     N      Mean        SD        SE  95% Conf.  Interval
0  reading_score  18.0  3.522222  1.104832  0.260411   2.972802  4.071642
1  reading_score  10.0  5.660000  1.079300  0.341305   4.887915  6.432085
2       combined  28.0  4.285714  1.498324  0.283157   3.704725  4.866704,                               Independent t-test  results
0  Difference (reading_score - reading_score) =   -2.1378
1                          Degrees of freedom =   26.0000
2                                           t =   -4.9452
3                       Two side test p value =    0.0000
4                      Difference < 0 p value =    0.0000
5                      Difference > 0 p value =    1.0000
6                                   Cohen's d =   -1.9504
7                                   Hedge's g =   -1.8936
8                              Glass's delta1 =   -1.9349
9                            Point-Biserial r =   -0.6962)

signifinance testing of feature: reading_score
t-test score: -4.9452
p-value: 0.000000000000000
difference between dyslexic and nondyslexic: significant

/Users/tzp466/miniconda3/lib/python3.9/site-packages/researchpy/ttest.py:38: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  groups = group1.append(group2, ignore_index= True)